import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { Carousel } from 'react-responsive-carousel';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Jwala</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <section className="">
        <Carousel showThumbs={false} >
          <div className='h-[80vh]  '>
            <div className='z-10 relative h-full py-20  '>

              <h1 className='text-xl text-white pt-16 py-4  w-[80%] justify-center m-auto ' >This will be our heading Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ab totam tempora maiores officiis tempore quod nemo incidunt aspernatur et consequuntur sapiente ducimus quis perferendis optio, impedit mollitia architecto animi.</h1>
              <p className='text-white py-4  w-[80%] justify-center m-auto '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam debitis iste dolore amet aliquam labore numquam praesentium commodi impedit, autem in suscipit hic quidem exercitationem sapiente explicabo repudiandae unde inventore! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum, fugit soluta cumque sunt itaque vitae sapiente quasi eius eum a enim saepe obcaecati optio praesentium provident voluptatem nesciunt odio. Exercitationem. </p>
            </div>
            <img
              className='h-[100%] absolute top-0 left-0 bg-cover'
              src="images/i4.jpg"
              alt="..."
            />
          </div>
          <div className='h-[80vh]  '>
            <div className='z-10 relative h-full py-20  '>

              <h1 className='text-xl text-white pt-16 py-4  w-[80%] justify-center m-auto ' >This will be our heading Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ab totam tempora maiores officiis tempore quod nemo incidunt aspernatur et consequuntur sapiente ducimus quis perferendis optio, impedit mollitia architecto animi.</h1>
              <p className='text-white py-4  w-[80%] justify-center m-auto '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam debitis iste dolore amet aliquam labore numquam praesentium commodi impedit, autem in suscipit hic quidem exercitationem sapiente explicabo repudiandae unde inventore! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum, fugit soluta cumque sunt itaque vitae sapiente quasi eius eum a enim saepe obcaecati optio praesentium provident voluptatem nesciunt odio. Exercitationem. </p>
            </div>
            <img
              className='h-[100%] absolute top-0 left-0'
              src="images/i1.jpg"
              alt="..."
            />
          </div>
          <div className='h-[80vh]'>
            <div className='z-10 relative h-full py-20  '>

              <h1 className='text-xl text-white pt-16 py-4  w-[80%] justify-center m-auto ' >This will be our heading Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ab totam tempora maiores officiis tempore quod nemo incidunt aspernatur et consequuntur sapiente ducimus quis perferendis optio, impedit mollitia architecto animi.</h1>
              <p className='text-white py-4  w-[80%] justify-center m-auto '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam debitis iste dolore amet aliquam labore numquam praesentium commodi impedit, autem in suscipit hic quidem exercitationem sapiente explicabo repudiandae unde inventore! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum, fugit soluta cumque sunt itaque vitae sapiente quasi eius eum a enim saepe obcaecati optio praesentium provident voluptatem nesciunt odio. Exercitationem. </p>
            </div>
            <img
              className='h-[100%] absolute top-0 left-0'
              src="images/i2.jpg"
              alt="..."
            />
          </div>
          <div className='h-[80vh]  '>
            <div className='z-10 relative h-full py-20  '>

              <h1 className='text-xl text-white pt-16 py-4  w-[80%] justify-center m-auto ' >This will be our heading Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ab totam tempora maiores officiis tempore quod nemo incidunt aspernatur et consequuntur sapiente ducimus quis perferendis optio, impedit mollitia architecto animi.</h1>
              <p className='text-white py-4  w-[80%] justify-center m-auto '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam debitis iste dolore amet aliquam labore numquam praesentium commodi impedit, autem in suscipit hic quidem exercitationem sapiente explicabo repudiandae unde inventore! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illum, fugit soluta cumque sunt itaque vitae sapiente quasi eius eum a enim saepe obcaecati optio praesentium provident voluptatem nesciunt odio. Exercitationem. </p>
            </div>
            <img
              className='h-[100%] absolute top-0 left-0'
              src="images/i3.jpg"
              alt="..."
            />
          </div>




        </Carousel>
      </section>

      <section className="text-gray-400 bg-gray-900 body-font  " id="about">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-white">About Us
              <br className="hidden lg:inline-block" /><span className='underline'>Helping Farmer</span>
            </h1>
            <p className="mb-8 leading-relaxed">We are a group of tech geeks who uses technology to help farmer across the world to prevent/alert farmers from getting their crop burned . Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia, quia enim. Eos cupiditate, ipsam ex mollitia repellendus doloremque harum porro officia corrupti eius enim doloribus! Aut id qui beatae at iste enim ipsum, facilis, nihil voluptatibus tempore aliquid cupiditate non aperiam? Sapiente nihil harum beatae dicta voluptatum quaerat amet fugit! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sit fugiat voluptas perspiciatis fuga id iure deleniti unde mollitia corporis. Repudiandae unde suscipit alias eum repellendus eligendi officiis doloremque quibusdam similique? Tenetur necessitatibus hic, ipsam fugiat adipisci, iste pariatur nostrum eaque atque minima molestiae. Beatae doloremque, ipsa pariatur aliquid iure quis impedit animi possimus minima illum, at tempore. Sed, ut consectetur facilis asperiores itaque fugit vitae, voluptatem culpa quasi quos deserunt totam placeat quidem nobis quam, natus ad debitis ab atque. </p>

          </div>
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
            <img className="object-cover object-center rounded" alt="hero" src="images/i5.jpg" />
          </div>
        </div>
      </section>

      <section className="text-gray-600 body-font bg-black text-yellow-50" >
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-white">Hear it from Our Customer</h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">Whatever cardigan tote bag tumblr hexagon brooklyn asymmetrical gentrify, subway tile poke farm-to-table. Franzen you probably haven't heard of them man bun deep jianbing selfies heirloom.</p>
          </div>
          <div className="flex flex-wrap -m-4">
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center" src="images/c1.jpg" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-black opac opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-white mb-1">THE SUBTITLE</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">Shooting Stars</h1>
                  <p className="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center" src="images/c2.jpg" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-black opac opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-white mb-1">THE SUBTITLE</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">The Catalyzer</h1>
                  <p className="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center" src="images/c3.jpg" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-black opac opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-white mb-1">THE SUBTITLE</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">The 400 Blows</h1>
                  <p className="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center" src="images/c5.jpg" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-black opac opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-white mb-1">THE SUBTITLE</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">Neptune</h1>
                  <p className="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center" src="images/c6.jpg" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-black opac opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-white mb-1">THE SUBTITLE</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">Holden Caulfield</h1>
                  <p className="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>
            <div className="lg:w-1/3 sm:w-1/2 p-4">
              <div className="flex relative">
                <img alt="gallery" className="absolute inset-0 w-full h-full object-cover object-center" src="images/c4.jpeg" />
                <div className="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-black opac opacity-0 hover:opacity-100">
                  <h2 className="tracking-widest text-sm title-font font-medium text-white mb-1">THE SUBTITLE</h2>
                  <h1 className="title-font text-lg font-medium text-gray-900 mb-3">Alper Kamu</h1>
                  <p className="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="text-white bg-black body-font overflow-hidden" id="Pricing">
        <div className="contFainer px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-20">
            <h1 className="sm:text-4xl text-3xl font-medium title-font mb-2 text-white">Pricing</h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base text-gray-100">Whatever cardigan tote bag tumblr hexagon brooklyn asymmetrical.</p>
            
          </div>
          <div className="flex flex-wrap -m-4">
           
            <div className="p-4 xl:w-1/2 md:w-1/2 w-full">
              <div className="h-full p-6 rounded-lg border-2 border-gray-300 flex flex-col relative overflow-hidden">
                <h2 className="text-sm tracking-widest title-font mb-1 font-medium">BUSINESS</h2>
                <h1 className="text-5xl text-white leading-none flex items-center pb-4 mb-4 border-b border-gray-200">
                  <span>$56</span>
                  <span className="text-lg ml-1 font-normal text-gray-500">/mo</span>
                </h1>
                <p className="flex items-center text-gray-100 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-gray-400 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5"></path>
                    </svg>
                  </span>Vexillologist pitchfork
                </p>
                <p className="flex items-center text-gray-100 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-gray-400 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5"></path>
                    </svg>
                  </span>Tumeric plaid portland
                </p>
                <p className="flex items-center text-gray-100 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-gray-400 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5"></path>
                    </svg>
                  </span>Hexagon neutra unicorn
                </p>
                <p className="flex items-center text-gray-100 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-gray-400 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5"></path>
                    </svg>
                  </span>Vexillologist pitchfork
                </p>
                
                <button className="font-bold  text-xl mt-auto text-white justify-center bg-orange-500 border-0 py-2 px-4 w-full focus:outline-none hover:bg-orange-700 hover:shadow-white/lg rounded">
                  Subscribe 
                  
                </button>
                <p className="text-xs text-gray-100 mt-3">Literally you probably haven't heard of them jean shorts.</p>
              </div>
            </div>
            <div className="p-4 xl:w-1/2 md:w-1/2 w-full">
              <div className="h-full p-6 rounded-lg border-2 border-gray-300 flex flex-col relative overflow-hidden">
                <h2 className="text-sm tracking-widest title-font mb-1 font-medium">SPECIAL</h2>
                <h1 className="text-5xl text-white leading-none flex items-center pb-4 mb-4 border-b border-gray-200">
                  <span>$72</span>
                  <span className="text-lg ml-1 font-normal text-gray-500">/mo</span>
                </h1>
                <p className="flex items-center text-gray-100 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-gray-400 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5"></path>
                    </svg>
                  </span>Vexillologist pitchfork
                </p>
                <p className="flex items-center text-gray-100 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-gray-400 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5"></path>
                    </svg>
                  </span>Tumeric plaid portland
                </p>
                <p className="flex items-center text-gray-100 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-gray-400 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5"></path>
                    </svg>
                  </span>Hexagon neutra unicorn
                </p>
                <p className="flex items-center text-gray-100 mb-2">
                  <span className="w-4 h-4 mr-2 inline-flex items-center justify-center bg-gray-400 text-white rounded-full flex-shrink-0">
                    <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" className="w-3 h-3" viewBox="0 0 24 24">
                      <path d="M20 6L9 17l-5-5"></path>
                    </svg>
                  </span>Vexillologist pitchfork
                </p>
                
                <button className="font-bold  text-xl mt-auto text-white justify-center bg-orange-500 border-0 py-2 px-4 w-full focus:outline-none hover:bg-orange-700 hover:shadow-white/lg rounded">
                  Subscribe 
                  
                </button>
                <p className="text-xs text-gray-100 mt-3">Literally you probably haven't heard of them jean shorts.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}
